Fix running tests on Travis CI
Apparently the latest arch-travis no longer accepts a string in
arch.script:

-e:1:in `<main>': undefined method `join' for nil:NilClass (NoMethodError)
-e:1:in `<main>': undefined method `join' for "bash ./.ci/build.sh":String (NoMethodError)
-e:1:in `<main>': undefined method `join' for nil:NilClass (NoMethodError)

Try the pending fix mentioned at https://github.com/mikkeloscar/arch-travis/issues/60#issuecomment-524622508